FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install postgresql-client -y

RUN pip install pipenv

RUN mkdir /app
WORKDIR /app

# Install Python dependencies
ADD Pipfile Pipfile
RUN pipenv install --dev --skip-lock

ADD . /app/
